### ISSUE TITLE
Disk list and selection feature request for flash.sh

### ISSUE THREAD

**Issue by carlossvg** [LanderU/ScriptsRPi2-BBB#3]
I would be great if the script can list all the available disks and let you select one when it tries to flash the image in a wrong disk.

**Comment by LanderU** [comment]
Thanks @carlossvg, this [commit](https://github.com/LanderU/ScriptsRPi2-BBB/commit/ef85fce3755f0b538bd0ca3aa9e87e94809b2076) add this feature ;-)
